# Generated by Django 6.0 on 2026-01-17 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('current_points', models.IntegerField()),
            ],
            options={
                'db_table': 'drivers',
            },
        ),
        migrations.CreateModel(
            name='Races',
            fields=[
                ('round_number', models.IntegerField(primary_key=True, serialize=False)),
                ('gp_name', models.CharField(max_length=100, unique=True)),
                ('gp_fullname', models.CharField(max_length=250)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('distance', models.FloatField()),
                ('circuit_length', models.FloatField()),
                ('laps_number', models.IntegerField()),
            ],
            options={
                'db_table': 'races',
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('team', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('engine_supplier', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('constructor_points', models.IntegerField()),
                ('gp_points', models.IntegerField()),
                ('gp_wins', models.IntegerField()),
                ('gp_poles', models.IntegerField()),
                ('sprint_points', models.IntegerField()),
                ('sprint_wins', models.IntegerField()),
                ('sprint_poles', models.IntegerField()),
            ],
            options={
                'db_table': 'team_specifications',
            },
        ),
        migrations.CreateModel(
            name='FastestLapTimes',
            fields=[
                ('track_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('lap_time', models.TimeField()),
                ('driver_number', models.ForeignKey(db_column='driver_number', on_delete=django.db.models.deletion.CASCADE, to='f1project.drivers')),
                ('gp_name', models.ForeignKey(db_column='gp_name', on_delete=django.db.models.deletion.CASCADE, to='f1project.races', to_field='gp_name')),
            ],
            options={
                'db_table': 'fastest_lap_times',
            },
        ),
        migrations.AddField(
            model_name='drivers',
            name='team',
            field=models.ForeignKey(db_column='team', on_delete=django.db.models.deletion.CASCADE, to='f1project.teams'),
        ),
        migrations.CreateModel(
            name='RaceResults',
            fields=[
                ('gp_name', models.ForeignKey(db_column='gp_name', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='f1project.races', to_field='gp_name')),
                ('race_date', models.DateField()),
                ('laps_number', models.IntegerField()),
                ('race_time', models.TimeField()),
                ('winner_number', models.ForeignKey(db_column='winner_number', on_delete=django.db.models.deletion.CASCADE, to='f1project.drivers')),
            ],
            options={
                'db_table': 'race_results',
            },
        ),
    ]
